version: "3"

services:
  traefik:
    # The official v2.0 Traefik docker image
    image: traefik:latest
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    # command: --api --providers.docker
    ports:
      # The HTTP port
      - 80:80
      # The Web UI (enabled by --api)
      - 8080:8080
      - 443:443
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    networks:
      - web
    expose:
      - 8080
    labels:
      - "traefik.port=8080"
      - "traefik.backend=traefikception"
      - "traefik.frontend.rule=Host:bidart.wilders.dev"
      - "traefik.enable=true"

networks:
  web:
    external: true
